# Generated by Django 4.0.1 on 2022-03-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arikeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
