# Generated by Django 4.0.1 on 2022-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arikeuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='arikeuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
