# Generated by Django 4.0.1 on 2022-03-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palliative_phase', models.CharField(max_length=100)),
                ('blood_pressure', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('personal_hygiene', models.CharField(max_length=100)),
                ('mouth_hygiene', models.CharField(max_length=100)),
                ('systemic_examination', models.CharField(max_length=100)),
                ('systemic_examination_details', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('created_updated', models.DateTimeField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
