# Generated by Django 4.0.1 on 2022-03-05 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palliative_phase', models.CharField(max_length=100)),
                ('blood_pressure', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('personal_hygiene', models.CharField(max_length=100)),
                ('mouth_hygiene', models.CharField(max_length=100)),
                ('public_hygiene', models.CharField(max_length=100)),
                ('systemic_examination', models.CharField(max_length=100)),
                ('systemic_examination_details', models.CharField(max_length=100)),
                ('patient_at_peace', models.BooleanField(default=True)),
                ('pain', models.BooleanField(default=False)),
                ('symptoms', models.CharField(choices=[], max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2022, 3, 5, 20, 32, 35, 691374))),
                ('note', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
