# Generated by Django 4.0.1 on 2022-03-05 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 20, 56, 23, 701491)),
        ),
    ]
