# Generated by Django 4.0.1 on 2022-03-05 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_note_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 21, 4, 50, 888455)),
        ),
    ]
