# Generated by Django 4.0.1 on 2022-03-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_visit_nurse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Health_info',
            new_name='HealthInfo',
        ),
    ]
