# Generated by Django 4.0.1 on 2022-03-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_health_info_healthinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_updated',
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='pain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='patient_at_peace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 7, 7, 47, 290072)),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(default='xyz', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 5, 7, 7, 47, 290049)),
        ),
    ]
