# Generated by Django 4.0.1 on 2022-03-04 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 12, 46, 54, 622637)),
        ),
    ]
