# Generated by Django 4.0.1 on 2022-03-04 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_treatment_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='department',
            new_name='address',
        ),
        migrations.AddField(
            model_name='family',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='family',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='expired_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 19, 11, 48, 507927)),
        ),
    ]
