# Generated by Django 4.0.1 on 2022-03-04 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_department_patient_address_family_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='expired_time',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 19, 14, 42, 608580)),
        ),
    ]
