# Generated by Django 4.0.1 on 2022-03-04 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 19, 56, 4, 22237)),
        ),
    ]
