# Generated by Django 4.0.1 on 2022-03-04 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_treatment_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 4, 20, 4, 51, 132660)),
        ),
    ]
