# Generated by Django 4.0.1 on 2022-03-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_treatment_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 3, 5, 7, 7, 47, 286397)),
        ),
    ]
